// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPDEu5p2CYRDRaU9CsSbZRdqYo3vDaE34',
    appId: '1:656268951909:web:0ef0dc3f8759e94424e18c',
    messagingSenderId: '656268951909',
    projectId: 'guardnotifier-dcbdb',
    authDomain: 'guardnotifier-dcbdb.firebaseapp.com',
    storageBucket: 'guardnotifier-dcbdb.appspot.com',
    measurementId: 'G-HTZDDE3NVE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHk97c24T2WwruChc-EKaRI2YykC-uLqM',
    appId: '1:656268951909:android:c7a588b8a9fe277a24e18c',
    messagingSenderId: '656268951909',
    projectId: 'guardnotifier-dcbdb',
    storageBucket: 'guardnotifier-dcbdb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXWSzsE-leu7AIK_RaLLMPPNfOvuSZUEs',
    appId: '1:656268951909:ios:f094dd4b97a9266524e18c',
    messagingSenderId: '656268951909',
    projectId: 'guardnotifier-dcbdb',
    storageBucket: 'guardnotifier-dcbdb.appspot.com',
    iosClientId: '656268951909-pdlg08dhjb3272lgiaqdfgokcqg88lur.apps.googleusercontent.com',
    iosBundleId: 'com.example.guardNotifier',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXWSzsE-leu7AIK_RaLLMPPNfOvuSZUEs',
    appId: '1:656268951909:ios:9e6122d690be5c8724e18c',
    messagingSenderId: '656268951909',
    projectId: 'guardnotifier-dcbdb',
    storageBucket: 'guardnotifier-dcbdb.appspot.com',
    iosClientId: '656268951909-tmovsbvegqguja4satv2jk2jlij32qru.apps.googleusercontent.com',
    iosBundleId: 'com.example.guardNotifier.RunnerTests',
  );
}
